Repository Jas-SinghFSU/HyprPanel, pull requests merged in 2025-06, with the labels that each got.

#964 Add devShell to flake.nix (also update flake.lock)
  flake.lock
  flake.nix
Labels: nix

#981 fix: initialize media players on startup
  src/services/media/index.ts
Labels: bug

#985 feat: add ability to specify connector as layout name and extend other layouts
  src/components/bar/utils/monitors/index.ts
  src/lib/bar/helpers.ts
  src/lib/options/types.ts
  src/services/display/monitor/index.ts
Labels: enhancement
